# Generated by Django 3.1.1 on 2020-09-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_format', models.CharField(choices=[('Image', 'Image'), ('Youtube', 'Youtube'), ('Slide', 'Slide'), ('Video', 'Video')], default='Slide', max_length=100)),
                ('p_type', models.CharField(choices=[('Website', 'Website'), ('Mobile App', 'Mobile App'), ('Graphic', 'Graphic'), ('Digital Marketing', 'Digital Marketing')], default='Website', max_length=100)),
                ('project_name', models.CharField(default='', max_length=100)),
                ('client', models.CharField(default='', max_length=100)),
                ('link', models.URLField(blank=True, default='null')),
                ('duration', models.CharField(default='', max_length=100)),
                ('progress', models.CharField(choices=[('On-going', 'On-going'), ('Completed', 'Completed'), ('Submitted', 'Submitted')], default='', max_length=100)),
                ('tech', models.CharField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
