# Generated by Django 3.1.1 on 2020-09-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200922_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', null=True, upload_to='portfolio')),
                ('porfolio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.portfolio')),
            ],
        ),
    ]
