# Generated by Django 3.1.1 on 2020-09-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200922_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ManyToManyField(blank=True, to='website.SlideImage'),
        ),
    ]
