# Generated by Django 3.1.1 on 2020-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='display_image',
            field=models.ImageField(default='', null=True, upload_to='portfolio'),
        ),
    ]
