# Generated by Django 3.1.1 on 2020-09-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_portfolio_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='', max_length=100, null=True),
        ),
    ]
