# Generated by Django 3.1.1 on 2020-09-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
