# Generated by Django 3.1.1 on 2020-09-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_blog_comment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(default='', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('code', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
