# Generated by Django 3.1.1 on 2020-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200924_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcode',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
